#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.7.0.{build}-{branch}

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

clone_depth: 1

nuget:  
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build_script:
- dotnet --info
- dotnet restore --no-cache
- dotnet build --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%
- dotnet pack src/RestApiHelpers/RestApiHelpers.csproj --configuration Release --no-build

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
- dotnet test test/RestApiHelpers.Test/RestApiHelpers.Test.csproj --configuration Release -f netcoreapp1.0 --no-build

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: src/**/*.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  provider: NuGet
  api_key:
    secure: UrYYF7dW4tZvlgTcihdNHoURAdjBRAFUvbXO+Pt+772aQLVNtbjlDBY4BqvHBxcz
  skip_symbols: false
  artifact: /.*\.nupkg/
